org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76
neo_version_range=[26.1.2.76,)
sbl_version=1.17-alpha-1
geckolib_version=5.5.1

mod_id=bittermelon
mod_name=Bittermelon
mod_license=CC BY-SA 3.0
mod_version=development
mod_group_id=com.site21.bittermelon
mod_authors=SmokeyBBQ, Punster_Fish, EJB Pietersen, Nick10000, Axo3773, TheRealSubZero
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.