org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.180
neo_version_range=[21.1.0,)
loader_version_range=[4,)
geckolib_version=4.7.6

mod_id=bittermelon
mod_name=Bittermelon
mod_license=CC BY-SA 3.0
mod_version=0.0.0
mod_group_id=com.site21.bittermelon
mod_authors=SmokeyBBQ, EJB Pietersen, Nick10000
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.